[package]
name = "tessera-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
futures.workspace = true
gpui.workspace = true
image.workspace = true
tessera-audio.workspace = true
tessera-document.workspace = true
tessera-timeline.workspace = true
tessera-media.workspace = true
tessera-render.workspace = true
tracing.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
